# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 11, 16, 13, 58, 26, 297179, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
